---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-dns-source
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/kubernetes-sigs/external-dns.git
  ref:
    tag: v0.7.6
  ignore: |
    # exclude all
    /*
    # include deploy crds manifest
    !/docs/contributing/crd-source/crd-manifest.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns-crds
  namespace: flux-system
spec:
  interval: 5m
  prune: false
  sourceRef:
    kind: GitRepository
    name: external-dns-source
  healthChecks:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: dnsendpoints.externaldns.k8s.io
