---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-dns-source
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/kubernetes-sigs/external-dns.git
  ref:
    tag: v0.7.6
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns-crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./docs/contributing/crd-source/crd-manifest.yaml
  prune: false
  sourceRef:
    kind: GitRepository
    name: external-dns-source
