---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: rook-ceph-source
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/rook/rook.git
  ref:
    tag: v1.5.5
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook-ceph-crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/examples/kubernetes/ceph/crds.yaml
  prune: false
  sourceRef:
    kind: GitRepository
    name: rook-ceph-source
