---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kube-prometheus-stack-crd-source
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/prometheus-community/helm-charts.git
  ref:
    tag: kube-prometheus-stack-13.5.0
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/charts/kube-prometheus-stack/crds
