---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-crds
  namespace: flux-system
spec:
  interval: 5m
  prune: false
  sourceRef:
    kind: GitRepository
    name: kube-prometheus-stack-crds
  healthChecks:
  - apiversion: helm.toolkit.fluxcd.io/v1beta1
    kind: HelmRelease
    name: kube-prometheus-stack
    namespace: monitoring
  timeout: 2m
